SELECT 
    [CÓDIGO DO CLIENTE],
	[NOME DO CLIENTE],
	[REDE DE ENSINO],
    [CIDADE],
    [UF],
    SEGMENTO,
    [SÉRIE],
    [GRUPO COLEÇÃO],
    [CATEGORIA PADRONIZADA],
    SUM(CAST([FATURAMENTO SEM DESCONTO] AS NUMERIC (18, 2))) [FATURAMENTO_BRUTO],
    SUM(CAST([RECEITA] AS NUMERIC(18, 2))) AS [FATURAMENTO_LIQUIDO],
    SUM(CAST([VALOR TOTAL DESCONTO]AS NUMERIC(18, 2))) [VALOR TOTAL DESCONTO]
  FROM {{ ref('slv_cubo33_categorizado') }}
  WHERE
(
    [ANO DE UTILIZAÇÃO] = '2024'
    AND CODTMV NOT IN ('2.1.48', '2.2.76', '2.1.04')
    AND [TIPO DE PEDIDO] IN ('Acerto de NF', 'Adicional', 'D', 'Tiragem')
    AND NOT ANO = '2025'
    --AND [GRUPO COLEÇÃO] IN ('EU NO MUNDO', 'DIVE.B','CAMBRIDGE','COLEÇÃO PRINCIPAL')
)
GROUP BY [CÓDIGO DO CLIENTE],[NOME DO CLIENTE], [REDE DE ENSINO], [CIDADE], [UF], SEGMENTO, [SÉRIE], [GRUPO COLEÇÃO], [CATEGORIA PADRONIZADA]