SELECT 
    [CÓDIGO DO CLIENTE] AS [CÓDIGO DO CLIENTE],
    SEGMENTO,
    [GRUPO COLEÇÃO],
    [CATEGORIA PADRONIZADA],
    ROUND(SUM(CAST([VALOR TABELA] as float)), 2) AS [VALOR TABELA], 
    ROUND(SUM(CAST([FATURAMENTO SEM DESCONTO] as float)), 2) AS [FATURAMENTO SEM DESCONTO], 
    ROUND(SUM(CAST([RECEITA]as float)), 2) AS [RECEITA], 
    ROUND(SUM(CAST([VALOR TOTAL DESCONTO] AS float)), 2) AS [VALOR TOTAL DESCONTO]
FROM 
    {{ ref('slv_cubo33') }}
WHERE 
    [ANO DE UTILIZAÇÃO] = '2024' 
    AND CODTMV NOT IN ('2.1.48', '2.2.76', '2.1.04')
    AND [TIPO DE PEDIDO] IN ('Acerto de NF', 'Adicional', 'D', 'Tiragem')
	AND NOT ANO = '2025'
GROUP BY [CÓDIGO DO CLIENTE], SEGMENTO, [GRUPO COLEÇÃO], [CATEGORIA PADRONIZADA];