SELECT 
    [CÓDIGO DO CLIENTE],
    [NOME DO CLIENTE],
    [REDE DE ENSINO],
    [CIDADE],
    [UF],
    SUM([FATURAMENTO SEM DESCONTO]) AS [FATURAMENTO SEM DESCONTO],
    SUM([RECEITA]) AS [RECEITA],
    SUM([VALOR TOTAL DESCONTO]) AS [VALOR TOTAL DESCONTO]
FROM {{ ref('slv_cubo33_categorizado') }}
WHERE 
    [ANO DE UTILIZAÇÃO] = '2025'
    AND [ALUNO/PROFESSOR] = 'Aluno'
    AND CODTMV NOT IN ('2.1.48', '2.2.76', '2.1.04')
    AND [TIPO DE PEDIDO] IN ('Acerto de NF', 'Adicional', 'D', 'Tiragem')
GROUP BY [CÓDIGO DO CLIENTE], [NOME DO CLIENTE], [REDE DE ENSINO], [CIDADE], [UF]