SELECT 
    [ID da Escola]
    ,[Negociação Referente a]
    ,[Oportunidade Referente a]
    ,[Status da negociação]
    ,[Fase da Venda]
    ,[Data de Fechamento do Contrato]
    ,[Tempo de Contrato]
    ,[Quantidade de Alunos Negociados]
    ,[Receita Bruta]
    ,[Desconto Aplicado]
    ,[Valor do Frete]
    ,[Aporte]
    ,[Bonificação]
    ,[Total de Beneficios Concedidos]
    ,[Receita Liquida]
    ,[Margem Liquida]
    ,[Receita Consultor]
    ,[Consultor]
    ,[Coordenador]
    ,[Motivo da Perda]
    ,[Motivo da perda do Cross Selling]
    ,[Oportunidade Perdida para]
    ,[Ano de Utilização]
    ,[Data de Criação]
    ,[Temperatura do Cliente - Comercial]
    ,[Id Oportunidade]
    ,[Temperatura do Cliente - Cross]
  FROM {{ ref('slv_oportunidades_crm') }}
  WHERE [Ano de Utilização] = '2.026'