SELECT [accountid]
      ,[Nome Fantasia]
      ,[Quantidade Total de Alunos]
      ,[Rede de Ensino]
      ,[Situação do Cadastro]
      ,[Estado]
      ,[Cidade]
      ,[Bairro]
      ,[Ano da Rescisão]
      ,[Status do Cliente - Financeiro]
      ,[Início da Utilização]
      ,[Tipo de Relação]
      ,[Total Down Selling]
      ,[Categoria da Escola]
      ,[Escola referência na região]
      ,[Código RM]
      ,[Código INEP]
      ,[Código 1]
      ,[Data fim de contrato]
      ,[Data do Fim do Termo]
      ,[Curva ABCD]
      ,[Contrato perdido para]
      ,[Tipo de Atividade]
      ,[Perfil da escola]
      ,[Código Meu Bernoulli]
      ,[Sistema de Ensino]
      ,[Área de Atuação]
      ,[Cliente Plugbook?]
      ,[Início da Utilização Plugbook]
      ,[Escola em Serviço?]
      ,[Gerência Pedagógica Atual]
      ,[Consultor Pedagógico Atual]
      ,[Proprietário]
      ,[Liderança Regional]
      ,[Liderança Nacional]
      ,[Consultor Bilíngue Atual]
      ,[Forma de Blindagem]
      ,[Motivo da Rescisão]
      ,[Tipo de Rescisão]
      ,[Data da Formalização]
      ,[Alunos Perdidos]
      ,[Estimativa de Faturamento]
FROM {{ source ('intel_merc', 'brz_empresas') }} --{{ ref('slv_empresas_crm') }}
WHERE [Tipo de Relação] IN ('BSE - Em Processo de Rescisão','BSE - Ex-Cliente')