
version: 2

models:
  - name: gld_cubo33_2024
    description: "Pedidos e clientes filtrados para o ano de utilização 2024."
  - name: gld_cubo33_alunado
    description: "Número de alunos por escola."
  - name: gld_cubo33_2024_alunado
    description: "Número de alunos por escola em 2024."
  - name: gld_cubo33_2024_tkm
    description: "Tabela pronta para fazer Ticket Médio."
  - name: gld_2024_alunos_todos_produtos
    description: "Número de alunos por todos os produtos em 2024 considerando Inglês, Filosofia..."
  - name: gld_cubo33_2024_faturamento_produto
    description: "Faturamento por produto em 2024"
  - name: gld_cubo33_2023_faturamento_produto
    description: "Faturamento por produto em 2023"
  - name: gld_downselling_23_24_produto_faturamento
    description: "Base para cálculo de dowselling de faturamento por produto."
  - name: gld_downselling_23_24_produto_faturamento_resultado
    description: "Resultado cálculo de dowselling de faturamento por produto."
  - name: gld_cubo33_2024_alunos_todos_produtos_perfil
    description: "Número de alunos por todos os produtos em 2024 considerando Inglês, Filosofia... com perfil da escola."
  - name: gld_resultado_produtos_aluno_faturamento_2024
    description : "Resultado final de alunos, escolas e faturamento por escola, segmento, série."
  - name: gld_dec_vol_para_estimativa
    description : "Decréscimo em percuntal por columas de cada produto para ser utilizado no modelo de estimativa."
  - name: gld_2025_alunos_todos_produtos
    description: "Número de alunos por todos os produtos em 2025 considerando Inglês, Filosofia..."
  - name: gld_resultado_produtos_aluno_faturamento_2025
    description : "Resultado de 2025 de alunos, escolas e faturamento por escola, segmento, série."
  - name: gld_oportunidades_crm_2026
    description : "Oportunidades do CRM com ano de utilização de 2026"
  - name : gld_oportunidades_empresas
    desription : "Oportunidades já com as informações das escolas."
  - name : gld_escolas_pv
    description :  "Lista de escolas que usam material Pré Vestibular em 2025"
  - name : gld_escolas_pv_detalhado
  - name : gld_escolas_pv_old
  - name : gld_mapa_de_risco
  - name : gld_perguntas_mapa_de_risco
  - name : gld_empresas_matriz_e_risco
  - name : gld_2025_faturamento_escola
  - name : gld_registro_de_atendimento_detalhado
  - name : gld registro_de_atendimento