name: 'my_dbt_project'
version: '1.0'
config-version: 2

model-paths: ["models"]

profile: 'my_dbt_project'

models:
  my_dbt_project:  # Substitua pelo nome do projeto
    +sql_header: |
        SET ANSI_NULLS ON;
        SET QUOTED_IDENTIFIER ON;
        -- Define o collation padrão para todas as operações
        COLLATE SQL_Latin1_General_CP1_CI_AS;
    bronze:
      +materialized: table  # Bronze como tabela
    silver:
      +materialized: view # Silver como view
    gold:
      +materialized: view # Gold como view