
version: 2

models:
  - name: slv_escolas_bilingue
    description: "Modelo para selecionar escolas bilíngues e internacionais"
  - name: slv_cubo33
    description: "Tabela de pedidos corrigindo o formato de pedido da escola WR."
  - name: slv_grupo_colecao
  - name: slv_empresas_crm
    description: Empresas do CRM com seus respectivos ajustes no tipo de dado.
  - name: slv_segmentos_dos_clientes
    description: escolas do CRM com seus respectivos segmentos.
  - name: slv_empresas_blindadas
    description: Empresas blindadas no cm.
  - name: slv_censo_inep_media
    description: Base de escolas com a média de alunos por segmento para o dashboard de Inteligência de Mercado e Paper de Mercado.
  - name: slv_auditoria_de_visitas
    description: Tabela de visistas para o time de auditoria acompanhar datas de criação e da visita.
  - name: slv_auditoria_escola_sem_consultor
    description: Escolas que estão sem consultor para conferência pela auditoria.
  - name: slv_censo_inep_2024_publica_privada
    description: Base criada para o dashboard do Paper de Mercado.
  - name: slv_oportunidades_crm
    description: Oportunidades do CRM pronta para uso com correção do tipo de dado.
  - name: slv_censo_2024_latlong_inep
    description: Base do INEP enriquecida com latitude e longitude, utilizado no dashboard paper de mercado.