
version: 2

models:
  - name: slv_escolas_bilingue
    description: "Modelo para selecionar escolas bilíngues e internacionais"
  - name: slv_cubo33
    description: "Tabela de pedidos corrigindo o formato de pedido da escola WR."
  - name: slv_grupo_colecao
  - name: slv_empresas_crm
    description: Empresas do CRM com seus respectivos ajustes no tipo de dado.
  - name: slv_segmentos_dos_clientes
    description: escolas do CRM com seus respectivos segmentos.
  - name: slv_empresas_blindadas
    description: Empresas blindadas no cm.
  - name: slv_censo_inep_media
    description: Base de escolas com a média de alunos por segmento para o dashboard de Inteligência de Mercado e Paper de Mercado.
  - name: slv_auditoria_de_visitas
    description: Tabela de visistas para o time de auditoria acompanhar datas de criação e da visita.
  - name: slv_auditoria_escola_sem_consultor
    description: Escolas que estão sem consultor para conferência pela auditoria.
  - name: slv_censo_inep_2024_publica_privada
    description: Base criada para o dashboard do Paper de Mercado.
  - name: slv_oportunidades_crm
    description: Oportunidades do CRM pronta para uso com correção do tipo de dado.
  - name: slv_censo_2024_latlong_inep
    description: Base do INEP enriquecida com latitude e longitude, utilizado no dashboard paper de mercado.
  - name: slv_auditoria_novos_produtos_rm
    descripition: Tabela de auditoria para conferir a criação de novos produtos que não foram alinhados 
      e configurados na caregorização do produto.
  - name: slv_cubo33_filtrado
    descripition: Cubo 33 filtrando 'Aluno', CODTMV não seja ('2.1.48', '2.2.76', '2.1.04') e TIPO DE PEDIDO seja ('Acerto de NF', 'Adicional', 'D', 'Tiragem')
  - name: slv_empresas_com_cep
    description: Tabela de empresas do CRM enriquecida com informações do CEP.
  - name: slv_censo_inep_2024_particulares_enem
    description : Escolas do censo inep com nota enem.
  - name : slv_cubo33_aluno
    descripition : Cubo 33 já com os filtros de aluno.
  - name : slv_cubo33_produtos_nao_categorizados
    description : Produtos do cubo 33 que não está categorizado.
  - name : slv_aluno_potencial_integracao_crm_mb
    descption : "Tabela com o aluno pontecial no formato para a integração do CRM e Meu Bernoulli"