SELECT
    RIGHT('000000' + LEFT([CÓDIGO DO CLIENTE], CHARINDEX('.', [CÓDIGO DO CLIENTE] + '.') - 1), 6) AS [CÓDIGO DO CLIENTE],
    
    MAX(CASE WHEN [CATEGORIA PADRONIZADA] = 'COLEÇÃO PRINCIPAL' THEN 'Sim' ELSE 'Não' END) AS usa_colecao_principal,
    MAX(CASE WHEN [CATEGORIA PADRONIZADA] = 'EXTRA' THEN 'Sim' ELSE 'Não' END) AS usa_extra,
    MAX(CASE WHEN [CATEGORIA PADRONIZADA] = 'SIMULADO' THEN 'Sim' ELSE 'Não' END) AS usa_simulado,
    MAX(CASE WHEN [CATEGORIA PADRONIZADA] = 'MAKER' THEN 'Sim' ELSE 'Não' END) AS usa_maker

FROM {{ ref('gld_2025_alunos_todos_produtos') }}
GROUP BY RIGHT('000000' + LEFT([CÓDIGO DO CLIENTE], CHARINDEX('.', [CÓDIGO DO CLIENTE] + '.') - 1), 6)