SELECT 
    [ID da Escola]
    ,[Id Oportunidade]
    ,[Negociação Referente a]
    ,[Oportunidade Referente a]
    ,[Status da negociação]
    ,[Fase da Venda]
    ,CAST(TRY_PARSE([Data de Fechamento do Contrato] AS DATETIME USING 'pt-BR') AS DATE) AS [Data de Fechamento do Contrato]
    ,[Tempo de Contrato]
    ,CAST(CAST(REPLACE(REPLACE(ISNULL([Quantidade de Alunos Negociados], '0'), '.', ''), ',', '.') AS FLOAT) AS INT) 
    AS [Quantidade de Alunos Negociados]
    ,{{ convert_money_string_to_float('[Receita Bruta]') }} AS [Receita Bruta]
    ,{{ convert_money_string_to_float('[Desconto Aplicado]') }} AS [Desconto Aplicado]
    ,{{ convert_money_string_to_float('[Valor do Frete]') }} AS [Valor do Frete]
    ,{{ convert_money_string_to_float('[Aporte]') }} AS [Aporte]
    ,{{ convert_money_string_to_float('[Bonificação]') }} AS [Bonificação]
    ,{{ convert_money_string_to_float('[Total de Beneficios Concedidos]') }} AS [Total de Beneficios Concedidos]
    ,{{ convert_money_string_to_float('[Receita Liquida]') }} AS [Receita Liquida]
    ,{{ convert_money_string_to_float('[Margem Liquida]') }} AS [Margem Liquida]
    ,{{ convert_money_string_to_float('[Receita Consultor]') }} AS [Receita Consultor]
    ,[Consultor]
    ,[Coordenador]
    ,[Motivo da Perda]
    ,[Motivo da perda do Cross Selling]
    ,[Oportunidade Perdida para]
    ,[Ano de Utilização]
    ,PARSE([Data de Criação] AS DATETIME USING 'pt-BR') AS [Data de Criação]
    ,[Temperatura do Cliente - Comercial]
    ,[Temperatura do Cliente - Cross]
  FROM {{ source('intel_merc', 'brz_oportunidades') }}