SELECT
    CODCOLIGADA,
    ASSISTENTE,
    [CRIADO POR],
    APROVAÇÃO,
    [CÓDIGO DO CLIENTE],
    [FAT. P/ ESCOLA OU LIVRARIA],
    [CÓD. RM FATURAMENTO],
    [NOME DO CLIENTE],
    CIDADE,
    UF,
    [REDE DE ENSINO],
    [SOLICITAÇÃO CLIENTE],
    [DATA DE CRIAÇÃO],
    [DATA DE APROVAÇÃO],
    [CÓDIGO PRODUTO],
    DESCRIÇÃO,
    COLEÇÃO,
    VOLUME,
    ANO,
    CATEGORIA,
    [ALUNO/PROFESSOR],
    PROVA,
    PERNONALIZAÇÃO,
    CASE 
        WHEN [IDMOV] = 1834 
             AND [CODCOLIGADA] = 13 
             AND [CODTMV] IN ('1.2.18', '1.2.73') 
        THEN 'TIRAGEM' 
        ELSE [TIPO DE PEDIDO] 
    END AS [TIPO DE PEDIDO],
    [2º SEMESTRE],
    [TOTAL HISTÓRICO],
    [QUANTIDADE PEDIDO],
    [ANO DE UTILIZAÇÃO],
    [ID DO MOVIMENTO],
    CODTMV,
    STATUS,
    [VALOR TABELA],
    [FATURAMENTO SEM DESCONTO],
    CONVERT(MONEY, RECEITA) AS RECEITA,
    [% DESC GERAL] / 100 AS [% DESC GERAL],
    [VALOR TOTAL DESCONTO],
    [TIPO FRETE],
    VALORFRETE,
    [CONDIÇÃO DE PGTO],
    [UNIDADE ATENDIMENTO],
    [ID FAT],
    DISPONIBILIZAÇÃO,
    [MOTIVO DEVOLUCAO],
    [TOTAL ATUAL],
    [N DO MOVIMENTO],
    CONVERT(VARCHAR(10), [DATA DA CONFIRMAÇÃO DO CLIENTE], 103) AS [DATA DA CONFIRMAÇÃO DO CLIENTE],
    MÊS,
    [DATA DE APLICAÇÃO],
    [DATA BASE VENCIMENTO],
    RECEITA2,
    CODFILIAL
FROM
    {{ source('intel_merc', 'bi_venda_colecao_rm') }}
WHERE
    [DATA DE CRIAÇÃO] >= '2022-11-14'
    AND [DATA DE CRIAÇÃO] <= GETDATE()
    AND [ANO DE UTILIZAÇÃO] = 2024
    AND [ALUNO/PROFESSOR] = 'Aluno';